dist: xenial
language: python
sudo: false
python:
- 3.6
- 3.7
install:
- pip install -U pip setuptools pipenv==2018.10.13
- pipenv install -d --skip-lock
script:
- PYTHONPATH=. pytest
before_deploy:
- echo "__version__ = '$(git describe --tags)'" > aioworkers_orm/version.py
deploy:
  provider: pypi
  user: abogushov
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  skip_cleanup: true
  password:
    secure: sEDBFQZ5b9qEmVbesUXsBIWXYztzxR0hNOzq8Tv0lPxZgNthw89LMwmHGjYiLlDzsH+IL66zZ5PjLNksVy0AfJwl61nWbvSPh3N8TgdmEReT+v4in1VjRqTFbtv6o+/O2tDu4C2Ju5/CYDE15qtvRm5jnJ+t9mfzRyV9Lf3hTGdno/8aDjb7GIFDlddpAMYcQ6eYnzuCEp0Hfyq4dqQIIFwsNFqyU8dfJEIj5HYacNanO0QoWqB6SkJB7gobpmJZdLOWCI6/eINg92QYCQoG+pGjYQ0e5a6QVrmFbcMSs0q8NOUkmf/Mn1A0+hV9YbRIVjhzO2TMPHg7JW/dVzDZ9l6Cig9eW9tIAzk+BTiR+1LrsqcucPzB2tjIheadJLluwDWm3KPUICpUfrBBFzR5kURcsw+YMKrz2sQCJOGRuRWSZP/blKXiI8Sb9qxbtVmhXMppmzwrfKJ62vC75rpSctDqlTUnKcIJKl8p3+FBjNcK2aTtLL/r1WykaExuJt0HXogM1bCxh/njPpihuoh1xQaCuYaBz9py2fj0TzrazMQ8xZ9JU9Aq0SEPNkznOQH1KmrvdepBu5U3V5DsfFjmotkbJM7Ujzx8ZAw6e9EGZh3zDdkm6xDo83+31Q1bll1GErEg/aJONt8tGOH7jOLw3OdIwY45qxj6hrX+Y1hCVxE=
