dist: xenial
language: python
sudo: false

python:
- 3.6
- 3.7

install:
- pip install -U pip setuptools
- pip install pytest-runner

script:
- python setup.py test

before_deploy:
- echo "__version__ = '$(git describe --tags)'" > aioworkers_orm/version.py

deploy:
  provider: pypi
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.6"
  skip_cleanup: true
