name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install poetry
      run: pip install poetry
    - name: Install deps
      run: poetry install --no-root
    - name: Run pytest
      run: poetry run pytest --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
